default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  host: ec2-3-214-2-141.compute-1.amazonaws.com
  database: dglbrc5ipa19d  
  user: msktohrcqoxsbu
  port: 5432
  password: 6a1c0e9dbb068d0e1c5a668de79cd419cd845e3b6a7cd222eabbc32ce7ff3ca2

